In [2]:
str='212+212/162/162-'
str2='xxx-'
str3='3xx/4xx-399,392'

req, anti=str.split('-')
anti=anti.split(',')
new_req=req.split('/')
word_with_plus = next((word for word in new_req if "+" in word), None)
if word_with_plus:
                plus_course = word_with_plus.split('+')
                new_req.remove(word_with_plus)
                new_req.extend(plus_course)

print(new_req)

['162', '162', '212', '212']


In [5]:
req=[('MATH 407/411/440/441/446/449/477/499', '', '6', 'C-', '', ''), ('MATH 4xx', '', '6', 'C-', '', ''), ('MATH 3xx/4xx', '', '6', 'C-', '', ''), ('MATH 3xx/4xx', '', '6', 'C-', '', ''), ('General Elective', '', '6/8', 'D', '', '')]
course_req_open = [item for item in req if item[0] != "General Elective" and item[0] != "Open xxx"]

print(course_req_open)


[('MATH 407/411/440/441/446/449/477/499', '', '6', 'C-', '', ''), ('MATH 4xx', '', '6', 'C-', '', ''), ('MATH 3xx/4xx', '', '6', 'C-', '', ''), ('MATH 3xx/4xx', '', '6', 'C-', '', '')]


In [4]:
str='ANT 250-274/350-374/450-474'
c=245
req=str.split('|')
found=next((s for s in req if 'ANT' in s), None)
if found:
    codes=found.split(' ')[1].split('/')
print(codes)
for code in codes:
    if '-' in code:
        print(code.split('-'))
        if int(c[1:])>=int(code.split('-')[0][1:]) and int(c[1:])<=int(code.split('-')[1][1:]):
            print('yes')

['250-274', '350-374', '450-474']
['250', '274']
['350', '374']
['450', '474']


In [3]:
course_req_open=[('BIOL 3xx/4xx','','6/8','C-','BIOL 399 Biology Internship/BIOL 392 Directed Study in Biology',''),('BIOL 345','','6/8','C-','BIOL 399 Biology Internship/BIOL 392 Directed Study in Biology','')]
req_course='18|BIOL 3xx/4xx'
found=next((item for item in course_req_open if item[0] == req_course.split('|')[1]), None)
if found:
    print('yes')
    course_req_open.remove(found)
print(course_req_open)

yes
[('BIOL 345', '', '6/8', 'C-', 'BIOL 399 Biology Internship/BIOL 392 Directed Study in Biology', '')]


In [1]:
course='WLL 273|HST 273|LING 273/274'
target='HST'
req=course.split('|')
found=next((s for s in req if target in s), None)
if found:
    codes=found.split(' ')[1].split('/')
print(codes)
for code in codes:
                if code=='xxx':
                        print('xxx')
                       
                elif code.endswith('xx'):
                    if target[0]+' '+target[1] not in course[4]:
                        if code[0]==target[1][0]:
                            print
                        else:
                            continue
                elif code==target[1]:
                    if target[3] in course[2]:
                        if (target[4] in grades and (grades[target[4]] >= grades.get(course[3], 0))) or target[4]=='in progress' or target[4]=='P':
                            courses_passed.append(course)
                            return (True, 'open',course)
                        else:
                            return (False, 'open',course)
                else:
                    continue

['273']


In [6]:
import numpy as np
number_transmitters=int(input('Please enter the number of transmitters (2,3 or 4): '))
# chip_seq=[]
if number_transmitters not in [2,3,4]:
    print('Invalid number of transmitters')
else:
    chip_length = 4 if number_transmitters <= 3 else 8
    chip_seq=np.random.choice([1, -1], size=(number_transmitters, chip_length))
    print(chip_seq)

[[-1  1  1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]]


In [10]:
import numpy as np
data=np.array([int(input('Please enter the data to be transmitted: ')) for i in range(4)])
print(data)

[ 1 -1  1  1]


In [8]:
req = []
req1 = [('a', 'b', 'c'), ('d', 'e', 'f')]
# Check if req or req1 is empty and assign an empty string to the corresponding part in the combined string
combined_req = ((','.join(','.join(t) for t in req) + ';' if req else '') +
                ','.join(','.join(t) for t in req1))

print(combined_req)

a,b,c,d,e,f


In [8]:
str='212+212/162/162'
str1='Organic Chemistry II+Organic Chemistry II Laboratory/Physics II for Scientist and Engineers with Laboratory/Calculus II'

codes=str.split('/')
titles=str1.split('/')
code_with_plus = next((word for word in codes if "+" in word), None)
if code_with_plus:
    titles_with_plus = next((word for word in titles if "+" in word), None)
    plus_course = code_with_plus.split('+')
    plus_title = titles_with_plus.split('+')
    codes.remove(code_with_plus)
    titles.remove(titles_with_plus)
    codes.extend(plus_course)
    titles.extend(plus_title)
print(codes)
print(titles)

['162', '162', '212', '212']
['Physics II for Scientist and Engineers with Laboratory', 'Calculus II', 'Organic Chemistry II', 'Organic Chemistry II Laboratory']


In [4]:
str4='SEDS 3xx/4xx|SMG 3xx/4xx|MATH 3xx/4xx|PHYS 3xx/4xx|CHEM 3xx/4xx|ECON 3xx/4xx'
str=["ANT 140",'ANT 150', 'WCS 150']
# found= next((s for s in splitted if 'SEDS' in s), None)
# print(found)
# codes=found.split(' ')[1].split('/')
# print(codes)
if any("ANT" in s for s in str):
    for s in str:
        if "ANT" in s:
            print(s)


print(next((s for s in splitted if "SMG" in s), None))


ANT 140
ANT 150
SMG 3xx/4xx


In [3]:
import pandas as pd

# Sample data
data = {
    'patient_id': [1, 2, 3, 4, 5],
    'weight': [70, 65, 80, 75, 72],
    'height': [170, 165, 180, 175, 172],
    'age': [30, 35, 40, 45, 50],
    'diabetes': [False, True, False, True, True]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

print(df[df.diabetes == True]['age'].mean(),df[df.diabetes == False]['age'].mean())

print(df.g)

   patient_id  weight  height  age  diabetes
0           1      70     170   30     False
1           2      65     165   35      True
2           3      80     180   40     False
3           4      75     175   45      True
4           5      72     172   50      True
43.333333333333336 35.0


In [4]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,8,5])
print(np.mean((x-y)**2))

3.2
